---
website_title:   'WEB-PRA 1'
website_tagline: 'Jan André Schlösser (1085978)<br>Hanno Siebel (1082670)'
your_github_username: it4need
your_github_reponame: hsnr-web-pra
title: 'Projektinformationssystem'
lang:   de
date:   02.12.2018
author:
  - Jan André Schlösser
  - Hanno Siebel
header-includes: |
include-before: |
include-after: |
...
